package ua.mentoring.addressbook.tests;// Generated by Selenium IDE

import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import ua.mentoring.addressbook.model.GroupData;
import ua.mentoring.addressbook.model.Groups;

import java.io.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;

public class GroupCreationTests extends TestBase {

  @DataProvider
  public Iterator<Object[]> validGroups() throws IOException {
    List<Object[]> list = new ArrayList<Object[]>();
    BufferedReader reader = new BufferedReader(new FileReader(new File("src/test/resources/groups.csv")));
    String line = reader.readLine();
    while (line != null)
    {
      String[] split = line.split(";");
      list.add(new Object[] {new GroupData().withName(split[0]).withHeader(split[1]).withFooter(split[2])});
      line = reader.readLine();
    }
    return list.iterator();
  }

  @Test(dataProvider = "validGroups")
  public void testGroupCreation(GroupData group) {
    applicationManager.goTo().groupPage();
    Groups before = applicationManager.group().all();
    applicationManager.group().create(group);
    assertThat(applicationManager.group().count(), equalTo(before.size() + 1));
    Groups after = applicationManager.group().all();
    assertThat(after, equalTo(
            before.withAdded(group.withId(after.stream().mapToInt((g) -> g.getId()).max().getAsInt()))));

  }


  @Test
  public void testBadGroupCreation() {
    applicationManager.goTo().groupPage();
    Groups before = applicationManager.group().all();
    GroupData group = new GroupData().withName("NewGroup'");
    applicationManager.group().create(group);
    assertThat(applicationManager.group().count(), equalTo(before.size() ));
    Groups after = applicationManager.group().all();

    assertThat(after, equalTo(before));

  }

}
