package ua.mentoring.addressbook.tests;// Generated by Selenium IDE
import org.testng.Assert;
import org.testng.annotations.Test;
import ua.mentoring.addressbook.model.GroupData;


public class GroupDeletionTests extends TestBase {

  @Test
  public void testGroupDeletion (){
    applicationManager.getNavigationHelper().gotoGroupPage();
    if (! applicationManager.getGroupHelper().IsThereAnyGroup()) {
      applicationManager.getGroupHelper().createGroup(new GroupData("NewGroup", "", ""));
    }
    int before = applicationManager.getGroupHelper().getGroupCount();
    applicationManager.getGroupHelper().selectGroup();
    applicationManager.getGroupHelper().deleteSelectedGroups();
    applicationManager.getGroupHelper().returnToGroupPage();
    int after = applicationManager.getGroupHelper().getGroupCount();
    Assert.assertEquals(after, before-1);
  }

}