package ua.mentoring.addressbook.tests;// Generated by Selenium IDE
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ua.mentoring.addressbook.model.GroupData;

import java.util.List;
import java.util.Set;


public class GroupDeletionTests extends TestBase {

  @BeforeMethod
  public void ensurePreconditions() {
    applicationManager.goTo().groupPage();
    if (applicationManager.group().all().size() == 0) {
      applicationManager.group().create(new GroupData().withName("Test group"));
    }
  }

  @Test
  public void testGroupDeletion () {
    Set<GroupData> before = applicationManager.group().all();
    GroupData deletedGroup = before.iterator().next();
    applicationManager.group().delete(deletedGroup);
    Set<GroupData> after = applicationManager.group().all();
    Assert.assertEquals(after.size(), before.size() -1);

    before.remove(deletedGroup);
    Assert.assertEquals(before, after);
  }



}