pipeline {
	
	agent any

	environment {
		//all variables defined here will be available inside Jenkinsfile
		NEW_VERSION = '1.3.0'
//		SERVER_CREDENTAILS = credentials('ID from Jenkins'), also required "credentials binding" plugin
	}

	triggers {
		 cron('H */8 * * *') //regular builds
	}

	tools {
		gradle 'Gradle' 
		jdk 'JDK'
	}

	parameters {
		choice(name: 'BROWSER', choices: ['chrome', 'firefox', 'safari', 'edge'], description:'Please select a browser you would like the tests to be run on')
		string(name: 'NUMBER_OF_RUNS', defaultValue: '1', description:'Please select how many time you would likt to re-run the tests')
		booleanParam(name: 'executeTests', defaultValue: true, description:'')
	}

	stages {

		stage("build") {
			steps {
				echo 'building the application...'
				gradle {
					tasks ('clean')
					tasks('build')
				}
			}
		}

		stage("test") {
			when {
				expression {
					params.executeTests == true 	//the part in steps will be executed only if this condition will be met
				}
			}
			steps {
				echo 'testing the application...'
				gradle {
					tasks('tunTests')
				}
			}
		}

		stage("deploy") {
			steps {
				echo 'deploying the application...'
				echo "tested on ${params.BROWSER} browser"
//				withCredentials([
//					usernamePassword('ID from Jenkins', usernameVaviable: USER, passwordVariable: PWD)
//					]) {
//					sh "some shell script ${USER} ${PWD}"
//				}
			}
		}
	}

}
